<?php

/*
 * THIS FILE INCLUDES ALL THE CLASSES AND IMPORTANT FILES
 * AND THEN LOADS THEM WITH AN ASSIGNED VARIABLE FOR
 * EASY ACCESS. IT IS BETTER ADVISED NOT TO TOUCH THIS
 * PLACE BECAUSE ANY ALTERATION MAY MAKE THIS SCRIPT
 * NOT WORK PROPERLY
 */

/*
 * CONFIGURATION FILE MUST BE AT FIRST BECAUSE SOME
 * INFORMATIONS ARE DECLARED IN IT AND MANY CHILD
 * CLASSES USE THE VARIABLES DECLARED IN THE CONFIG
 * FILE :)
 */

require __DIR__ . "/config/Config.conf.php";

/*
 * ALL OTHER LIBRARIES ARE LOADED AFTERWARDS
 */

// Libraries .....

/*
 * PRELOAD CLASSES THAT ARE MOST REQUIRED EVERY WHERE
 */

require __DIR__ . "/class/MessageHandler.class.php";

/*
 * ASSIGN VARIABLES TO THE CLASSES INSTALLED HERE
 */

$echo = new Logger();